// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxvzfrdwplcqaeomtlup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dnpmcmR3cGxjcWFlb210bHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzcxMzksImV4cCI6MjA2MzU1MzEzOX0.refGLLK_6sS2ebRvEWHxgldlrW0Ne5BvNyDe-7IO_RY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);